version: '3.8'

services:
  db:
    image: postgres:13
    container_name: FastFoodManager_db
    environment:
      POSTGRES_USER: fastfoodUser
      POSTGRES_PASSWORD: fastfoodPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
      POSTGRES_DB: fastfood